### ISSUE TITLE
Unable to add Koloda-Android dependeny in new Android Studio Bumblebee

### ISSUE THREAD

**Issue by Simba-97** [Yalantis/Koloda-Android#19]
Recently I updated my android studio to the new Bumblebee stable version and since then the root-level build.gradle file seems to have changed a lot. I'm facing issue with adding the dependencies in the build.gradle file and am not able to use it in the application
Attaching a few screenshots below so you can get a better understanding of my situation. @egoossens @DipanshKhandelwal @kstanislav  Can you guys help me out and let me know if I'm doing something wrong?
![Screenshot_20220213_085330](https://user-images.githubusercontent.com/55483056/153737023-1620f31c-61b0-4586-8c4e-f47d538a6a6a.png)
![Screenshot_20220213_085400](https://user-images.githubusercontent.com/55483056/153737025-9aa3be9e-eb48-4a2c-8f0a-0b8720b1953a.png)
![Screenshot_20220213_085434](https://user-images.githubusercontent.com/55483056/153737027-18899b12-c507-4d73-b366-b56515463ae5.png)

I'm developing using Kotlin, Androidx libraries

**Comment by JBJ75S** [comment]
Hi, I warmly recommend you to use this code, it's working : 
"
    <com.yalantis.library.Koloda
        android:id="@+id/koloda"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        app:koloda_card_layout="@layout/item_koloda"
        ...
        />
        "
        
        (Difference : "/>" instead of "> </com.yalantis.koloda-android>")

**Comment by Simba-97** [comment]
@JBJ75S Thank you so much for helping me out on this! 👍🏻

**Comment by JBJ75S** [comment]
You're welcome.
