### ISSUE TITLE
koloda.reloadPreviousCard() not found

### ISSUE THREAD

**Issue by pankaj210891** [Yalantis/Koloda-Android#4]
Hi There,

Recently, I faced a new issue i.e koloda.reloadPreviousCard() method is not in the library. So I am unable to load the previous card. Please fix this solution ASAP.

**Comment by pankaj210891** [comment]
It's almost about a month and I haven't received any response from Author.

**Comment by pokurivijay** [comment]
Same Problem...Please fix this solution ASAP.
